<?php

namespace DBBundle\Repository;

/**
 * AdminUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminUserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findpredata($name,$email,$mobile,$preid) {
        $saleQuery = "SELECT * FROM `adminuser` where (Name='".$name."' or Email='".$email."' or Mobile='".$mobile."') and id!=$preid";
        $stmt = $this->getEntityManager()->getConnection()->prepare($saleQuery);
        $stmt->execute();
        return $stmt->fetchAll();
    }
}
