<?php

namespace DBBundle\Repository;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends \Doctrine\ORM\EntityRepository
{
    public function findtodayusers() {
        $saleQuery = "SELECT Count(*) as users FROM `users` where DATE(DateCreated)=CURDATE()";
        $stmt = $this->getEntityManager()->getConnection()->prepare($saleQuery);
        $stmt->execute();
        return $stmt->fetch();
    }
    public function findusers($mobile) {
        $saleQuery = "SELECT *  FROM `users` where mobile=$mobile";
        $stmt = $this->getEntityManager()->getConnection()->prepare($saleQuery);
        $stmt->execute();
        return $stmt->fetchAll();
    }
}
