<?php

namespace DBBundle\Repository;

/**
 * UserroleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserroleRepository extends \Doctrine\ORM\EntityRepository
{

 public function findpredata($name,$preid) {
        $saleQuery = "SELECT * FROM `userrole` where name='".$name."' and id!=$preid";
        $stmt = $this->getEntityManager()->getConnection()->prepare($saleQuery);
        $stmt->execute();
        return $stmt->fetchAll();
    }


}
